### ISSUE TITLE
A walkthrough the first Bunsen APK

### ISSUE THREAD

**Issue by chrisekelley** [bunsenbrowser/bunsen#20]
Install the [Bunsen APK](https://github.com/bunsenbrowser/bunsen/raw/master/apk/bunsen.apk) either by moving it to your mobile device or by using the adb command:

```
adb install bunsen.apk
```

Launch Bunsen. It will display a loading screen:

![screenshot_20170814-124442-40size](https://user-images.githubusercontent.com/861535/29268991-8f72aebe-80ef-11e7-9b1d-1a2ac39860fd.png)

Once it has finished it will display a screen welcoming the user to download a dat:

![screenshot_20170814-124503-40sizey](https://user-images.githubusercontent.com/861535/29269055-e67bf1de-80ef-11e7-8fb9-3e61884837a7.png)

To load a dat, hit the go (forward symbol pointing to the right) button. A "downloading" dialog is displayed:

![bunsen-downloading-dialog](https://user-images.githubusercontent.com/861535/29269189-85d966d0-80f0-11e7-8d74-70d288940854.png)

The demo app will soon display.

![bunsen-tang-v3-demo](https://user-images.githubusercontent.com/861535/29269201-90e63300-80f0-11e7-820b-3debe3ddc65d.png)

To delete a dat, press the hamburger menu and select Delete Installed Application. 

![bunsen-delete](https://user-images.githubusercontent.com/861535/29269209-97a57f52-80f0-11e7-9c71-bbf78c0f1c6e.png)

**Comment by rjsteinert** [comment]
w00t! https://goo.gl/photos/JcxaXoPkGKisjiZEA

**Comment by chrisekelley** [comment]
Updated screenshots of initial app load
Created wiki page and copied this walkthrough over to it: https://github.com/bunsenbrowser/bunsen/wiki/Bunsen-Walkthrough

**Comment by chrisekelley** [comment]
Now that we have an (outdated) walkthrough in the wiki, this issue is no longer relevant. Closing.
