### ISSUE TITLE
Build options to preload a Dat, change APK name, and remove Bunsen UI

### ISSUE THREAD

**Issue by rjsteinert** [bunsenbrowser/bunsen#29]
This would Apps to be distributed offline as APKs, launch as that App from the homescreen/app drawer, avoid issues of losing that Dat due to the current one Dat limit, and keep the user focused on that one App.

I'm not super excited about this compared to actually improving Bunsen, but it would allow projects to use Bunsen/Dat without the pitfalls until Bunsen is fully fleshed out.

**Comment by chrisekelley** [comment]
Thanks to your cool cat-eating-it's-own-tail trick of having the Bunsen Ui be a dat, we have implemented a part of this proposed functionality. We also now can support caching multiple dats thanks to dat-gateway. Closing.
