### ISSUE TITLE
Install fails on Android with chip architecture ARMv7 but not AArch64

### ISSUE THREAD

**Issue by rjsteinert** [bunsenbrowser/bunsen#31]
## Fails with ARMv7
```
➜  bunsen git:(master) ✗ adb install apk/bunsen.apk
apk/bunsen.apk: 1 file pushed. 4.5 MB/s (25476222 bytes in 5.428s)
	pkg: /data/local/tmp/bunsen.apk
Failure [INSTALL_FAILED_NO_MATCHING_ABIS]
```
![screen shot 2017-08-24 at 11 33 55 pm](https://user-images.githubusercontent.com/156575/29698684-66cd5e44-8925-11e7-9be9-c6ec1cf15a3e.png)

## Success with AArch64
![screen shot 2017-08-24 at 11 36 40 pm](https://user-images.githubusercontent.com/156575/29698692-74293248-8925-11e7-8de9-d4122bb7d197.png)

**Comment by chrisekelley** [comment]
A couple weeks ago I did some more work on compiling node 8.x on Termux. I managed to compile it; however, I didn't link it properly. This [Native Gradle Sample](https://github.com/janeasystems/nodejs-mobile-samples/tree/master/android/native-gradle) - shows how to create native-lib.cpp and should help close the gap. Kudos to [nodejs-mobile](https://github.com/janeasystems/nodejs-mobile)!

**Comment by chrisekelley** [comment]
A nice primer on using C/C++ code with node, and the build process part is especially useful: https://medium.com/@tarkus/how-to-call-c-c-code-from-node-js-86a773033892

**Comment by rjsteinert** [comment]
We could replace https://github.com/bunsenbrowser/cordova-node-plugin with https://github.com/janeasystems/nodejs-mobile-cordova.

**Comment by chrisekelley** [comment]
Is this resolved with the new https://github.com/janeasystems/nodejs-mobile-cordova plugin?

**Comment by chrisekelley** [comment]
I'm going to close this issue - I think by using nodejs-mobile-cordova plugin, we're supporting a wider range of devices.
