### ISSUE TITLE
Install fails on Moto G5

### ISSUE THREAD

**Issue by peregrinogris** [bunsenbrowser/bunsen#37]
I believe the Moto G5 is ARMv8, but somehow after trying to install Bunsen I just get a "Not compatible with you device" message.

**Comment by chrisekelley** [comment]
Hi - thanks for trying it out! I've been concerned about CPU compatability. Did you build from master? Over the weekend I created a new branch which uses the nodejs-mobile-cordova plugin and should have better CPU compat. 

https://github.com/bunsenbrowser/bunsen/tree/nodejs-mobile-cordova-refactor

I've only tested on a PIxel 2, and it worked there. I can send you a link to download the apk if you like; it's too big to upload to github.

**Comment by chrisekelley** [comment]
I just created a wiki page for device compatibility:

https://github.com/bunsenbrowser/bunsen/wiki/Device-testing

**Comment by chrisekelley** [comment]
You can download the new version here: [Download here!](https://drive.google.com/file/d/1JXT6xSV2r6OXi-A_0PXvh0IX8ks_dv9O/view?usp=sharing)

**Comment by peregrinogris** [comment]
Thanks for making a new build! I don't have any setup to build android apps, but I tried this new one and it works. I'll add my phone specs to the wiki.

![screenshot_20180411-144603](https://user-images.githubusercontent.com/115484/38634012-bc3bd032-3d97-11e8-9d34-c7053d1ab641.png)

**Comment by chrisekelley** [comment]
Cool, glad it works on your device. Thanks a lot for checking out Bunsen!

**Comment by peregrinogris** [comment]
@chrisekelley I think I can't edit the wiki for phone support, but I'll leave you the specs here:

## Moto G5
April 11, 2018

I tested an apk from the nodejs-mobile-cordova-refactor on a Moto G5 running Android 7.0 and it worked.Specs:

```
Chipset | Qualcomm MSM8937 Snapdragon 430
CPU | Octa-core 1.4 GHz Cortex-A53
GPU | Adreno 505
```

**Comment by chrisekelley** [comment]
Thanks a lot! I added your text to the device testing page. Sorry you weren't able to add it directly. I went into the Settings just now and I  *think* I updated edit access to the wiki for all.

Cheers - 

Chris
