### ISSUE TITLE
Switch frameworks for the bunsen shell?

### ISSUE THREAD

**Issue by chrisekelley** [bunsenbrowser/bunsen#39]
I coded bunsen's shell in Angular2. I'd like to rub off some rough edges, and since Angular is now at 5, it might make sense to upgrade it. But please chime in if it would be useful to switch to another framework. The shell doesn't have a lot going on. IMHO it would be nice to have a simpler, more hackable framework.

I'd prefer to have as small/easily hackable a framework as possible, and use Polymer3 custom elements if they would work for this. 

What are folks using for their beaker apps?

**Comment by chrisekelley** [comment]
I've upgraded the angular code to the latest 5.x. I pared back some of the angular-specific features like dialog. For now, let's keep it as it is and focus on implementing new features - like hosting multiple dats and seeing status of network sharing. Maybe we can implement these hew features in custom webcomponents, since Angular5 supports them.

**Comment by rjsteinert** [comment]
We've got new digs!
Default landing page, needs work...
<img width="412" alt="screen shot 2018-04-13 at 12 15 39 am" src="https://user-images.githubusercontent.com/156575/38716739-5cee31f0-3eb0-11e8-94a3-3ceae8cfd879.png">

Start typing a dat address and now there is a delete button. To execute on the address hit enter (same as chrome for Android).
<img width="432" alt="screen shot 2018-04-13 at 12 16 13 am" src="https://user-images.githubusercontent.com/156575/38716755-70aab844-3eb0-11e8-984f-ba92424be870.png">

There it is. Opened up. Could probably improve this, make Bunsen less in your face.
<img width="425" alt="screen shot 2018-04-13 at 12 16 34 am" src="https://user-images.githubusercontent.com/156575/38716773-922f93d6-3eb0-11e8-8351-7326d113039d.png">

And here is another address...
<img width="424" alt="screen shot 2018-04-13 at 12 17 36 am" src="https://user-images.githubusercontent.com/156575/38716801-bb17a2de-3eb0-11e8-8536-48e450892005.png">

Hey look! I'm entering another address and now I see I have history that I can tap on! Formatting needs work. Hard to tell one address from the other. Maybe some use of `feelbetterkittty-rjsteinert.hashb...`.

<img width="431" alt="screen shot 2018-04-13 at 12 18 04 am" src="https://user-images.githubusercontent.com/156575/38716826-d988eca0-3eb0-11e8-8b77-aec43378d129.png">

**Comment by chrisekelley** [comment]
So: we've switched to a minimal Angular5 shell that handles intents and fetching the Bunsen UI, which is coded as a Polymer webcomponent. The Bunsen UI is a dat, so it can be updated without having to download a new APK!
