### ISSUE TITLE
Number of Issues

### ISSUE THREAD

**Issue by fsteff** [bunsenbrowser/bunsen#49]
I tried bunsen today on my huawei p9 lite.
The demo page (that game) worked great, however I stumbled over a number of issues:

- I cannot navigate to other pages using the navigation bar, it always loads the demo page.
- When I load dat://beakerbrowser.com using firefox it loads that page on bunsen, however it seems not to be able to load any further resources (css files, images). (Not sure if that´s a bug or only not yet implemented, but here´s I solved that problem before: [https://github.com/fsteff/dattp](https://github.com/fsteff/dattp))

**Comment by rjsteinert** [comment]
Hi @fsteff - Thanks for the feedback. That first issue is one I started to run into last night as well, I haven't tracked down the route of the cause but I'm starting to think it's a the gateway level. For the second issue, that's a problem where dat sites assume they will be loaded up at the root of a domain but through the gateway they are actually one level deep at `http://localhost:3000/<dat uuid>/index.html` so any CSS or Script tags that start with `/` are not going to resolve to their resources. The good news is we have big updates coming for the gateway that I think are going to fix these problems! We're adopting @RangerMauve's fork of dat-gateway.

**Comment by rjsteinert** [comment]
Related https://github.com/bunsenbrowser/bunsen-ui/issues/6

**Comment by rjsteinert** [comment]
@fsteff Check out the latest APK https://drive.google.com/file/d/1GRlzMzjitL27tyahs2qfkm8QvZneWS_z/view?usp=sharing

This update requires a reinstallation of the APK while other UI related updates get updated over Dat on restart of the App. I think we have a fix for the issue of not being able to escape from home but we still have to implement the new gateway that puts dats at the root of the domain as to not break sites that expect that.

**Comment by RangerMauve** [comment]
@rjsteinert I took yesterday off from any tech stuff, so sorry for the absence. Do you need any help setting up my gateway? I got it working properly on the `lvh.me` domain along with subdomains.

The gateway does redirection to the subdomains automagically, so you don't have to do anything special at the app side. Load `lvh.me/{datkey}` and it will automatically redirect to `{base32key}.lvh.me`

**Comment by chrisekelley** [comment]
@rjsteinert - I'm closing this issue, looks like it's resolved.

**Comment by rjsteinert** [comment]
@RangerMauve That's great! Let's do it. Putting questions and notes over in the Security issue https://github.com/bunsenbrowser/bunsen/issues/30
