### ISSUE TITLE
Memory Problem

### ISSUE THREAD

**Issue by fsteff** [bunsenbrowser/bunsen#56]
Just found out that bunsen needed ~1GB of space on my phone.
I did not use it lately (and not much at all), so I am pretty sure this is a bug.

My pity that I forgot to check what exactly happened before I deleted the app... (got a warning that I did not have any free memory anymore).

**Comment by chrisekelley** [comment]
wowie - sorry about that :-) We're going through a major re-org; we will certainly create some new, interesting bugs, but I'll keep an eye on fs usage. On the version you're using, a nodejs plugin is storing dats on the filesystem. We probably don't have any limits on how much space it can take...

**Comment by chrisekelley** [comment]
I just put out a new release that could help this issue- I reduced in dat-gateway config the number of dats stored to 20. https://github.com/bunsenbrowser/bunsen/releases/tag/1.1.1

The bad news is that the APK is twice the size of the previous one...
