### ISSUE TITLE
Use GitHub releases to share apk files

### ISSUE THREAD

**Issue by gkrishnaks** [bunsenbrowser/bunsen#57]
Please use GitHub releases to share apk files. Currently I noticed that Google drive is used.

**Comment by chrisekelley** [comment]
Good idea - I thought we'd hit a file size limit for those, but we should be fine. We'll also release it on Play store.

**Comment by chrisekelley** [comment]
I just made a new release here: https://github.com/bunsenbrowser/bunsen/releases/tag/0.9.0 . It is very much an interim release - switching from Angular to less opinionated js code. Nothing new here, probably more bugs. Anyway, thanks for the suggestion!

**Comment by gkrishnaks** [comment]
Cool, @chrisekelley! :)
I tested it and updated this page : https://github.com/bunsenbrowser/bunsen/wiki/Device-testing
