### ISSUE TITLE
Release apks via dat

### ISSUE THREAD

**Issue by tswast** [bunsenbrowser/bunsen#58]
Similar to #57, but I'd actually like to see it distributed via dat and installed via https://github.com/staltz/dat-installer/ I don't like granting permission to install apps to my web browser.

**Comment by chrisekelley** [comment]
Yeah, stalz/s dat-installer is perfect for this. Next release we'll do this - I have already done some work getting our release pipeline sorted for Play store, and will set package it up for dat and Github releases too.

**Comment by chrisekelley** [comment]
I just release Bunsen as a dat archive:

via [hashbase dat link](dat://bunsen-apk.hashbase.io) 
or via [dat installer link](dat://0c3273b377f2535f499422f3f1cdbb31d009efea4d0db5b324d9f83aa0cb870b/)

I couldn't get it to work using https://github.com/staltz/dat-installer/  - it couldn't find it, even though it was on hashbase.io. I tried both the short hashbase link and the uuid.
