### ISSUE TITLE
URL bar will not go to dat address until after clicking on a dat link first

### ISSUE THREAD

**Issue by rjsteinert** [bunsenbrowser/bunsen#61]
The URL bar that is presented on first application load does not allow me to change the address. I type out a new address, press enter, then the address changes back to dat://home-bunsen.hashbase.io/.  However, when I click on a Dat link, the styled URL bar appears and I can enter dat addresses.

**Comment by chrisekelley** [comment]
I think I've fixed this in the new release, [1.1.1](https://github.com/bunsenbrowser/bunsen/releases/tag/1.1.1).
