### ISSUE TITLE
DatArchive API

### ISSUE THREAD

**Issue by arni077** [bunsenbrowser/bunsen#62]
everything related to DatArchive i tried to work with bunsen on my phone is still not working with my experimental website( e.g: DatArchive.create() and all the rest of the functions also ) .
my experimental website run those functions perfectly without any errors with beaker browser.

**Comment by RangerMauve** [comment]
Hi, the DatArchive API support is still a work in progress. You can track it in https://github.com/bunsenbrowser/bunsen/issues/53
