### ISSUE TITLE
what is the minimum requirement of Android version? 

### ISSUE THREAD

**Issue by steko** [bunsenbrowser/bunsen#63]
I had the previous beta installed on my Android 7.0 device.

The newly released 1.1 version from Google Play is unavailable for my device.

The APK from GitHub gives a generic "Error during the package analysis".

Thanks!

**Comment by chrisekelley** [comment]
@steko - the Play store has been pushing apps to support Android 8; looks like I got too strict with the config. I'll resolve this over the weekend.

**Comment by chrisekelley** [comment]
Sorry it took so long - it was a lot more complicated than expected. I had to make some changes to the gradle files for the nodejs-mobile-cordova to get the Google Play store to accept the APK. It's available there as well as here: https://github.com/bunsenbrowser/bunsen/releases/tag/1.1.2. Please tell me if you're having issues installing it on your device.
