### ISSUE TITLE
DatArchiveInfo.isOwner should be true for archives you DatArchive.create()

### ISSUE THREAD

**Issue by rjsteinert** [bunsenbrowser/bunsen#73]
Running the tests, for an archive that you create, you should be the owner. This is how an app knows whether or not it can write to an Archive. 

<img width="1440" alt="screen shot 2018-11-26 at 6 11 45 am" src="https://user-images.githubusercontent.com/156575/49010848-7651ad80-f142-11e8-96d7-690680fa0fc8.png">

**Comment by chrisekelley** [comment]
So - I was assuming that getInfo was a function similar to readFile, where you don't necessarily need to use the secret_keys. But you've identified that getInfo needs to access them in order to populateisOwner correctly (and not have it simply be false). Thanks!
