### ISSUE TITLE
Access to debugger

### ISSUE THREAD

**Issue by oelmekki** [bunsenbrowser/bunsen#85]
Hi there,

Thanks a lot for Bunsen, it looks very awesome!

I'm trying to build applications that I can both use on my laptop with Beaker and my mobile with Bunsen. When trying to run apps on Bunsen, I'll often get white pages because this or that thing won't be supported. Problem is, it's incredibly hard to tell what is the failing part, since I can't see any error.

I realized we should be able to access the console using adb debugging and the `chrome://inspect/#devices` page in chrome, but while I can indeed connect to my phone, Bunsen won't appear in apps I can debug. I suppose it's because it's a production build.

I tried building Bunsen myself, but I keep failing, having no experience in android development, let alone cordova development. Plus, it seems a bit overkilled doing that just to access the javascript console.

If the problem is indeed that the build does not include debugging info, is there any chance you release on github's release page APKs with debugging symbols included?

Thanks!

**Comment by rjsteinert** [comment]
> If the problem is indeed that the build does not include debugging info, is there any chance you release on github's release page APKs with debugging symbols included?

That's a great idea! @chrisekelley Do you have a recent debug build handy?

**Comment by chrisekelley** [comment]
Welcome @oelmekki !

I just uploaded a debug apk:

https://github.com/bunsenbrowser/bunsen/releases/tag/1.14

I'll try to release debug apks with each new release.
